name: cloud-annotation-tool
version: '0.1'
base: core18
summary: Single-line elevator pitch for your amazing snap
description: This is my-snap's description. You have a paragraph or two to tell the
grade: devel
confinement: devmode

apps:
  cloud-annotation-tool:
     command: desktop-launch cloud_annotation_tool

parts:
  vtk:
    plugin: cmake
    source: https://github.com/Kitware/VTK.git
    source-type: git
    source-branch: v8.1.1
    configflags:
      - -DCMAKE_BUILD_TYPE=Release 
      - -DBUILD_TESTING=OFF 
      - -DVTK_Group_Qt=ON 
      - -DVTK_Group_Rendering=ON 
      - -DVTK_Group_Views=ON 
      - -DVTK_Group_MPI=ON 
      - -DVTK_PYTHON_VERSION=3 
      - -DVTK_WRAP_PYTHON=ON
    stage-packages:
      - qt5dxcb-plugin
      - libqt5gui5
      - libpng16-16
      - libqhull7
      - libqt5opengl5
      - libqt5x11extras5
      - libswscale4
      - libavformat57
      - libopenni0
      - libopenni2-0
      - python3-minimal
      - libxt6
      - libhwloc5
      - libltdl7
      - libopenmpi2
      - libpython3.6
    build-packages: 
      - build-essential 
      - cmake 
      - qttools5-dev-tools 
      - libqt5opengl5-dev 
      - libqt5x11extras5-dev 
      - qtbase5-dev 
      - python3-dev 
      - python3-pip 
      - git 
      - wget
      - unzip 
      - yasm 
      - libpng-dev 
      - libavformat-dev 
      - libtiff-dev 
      - libswscale-dev 
      - llvm-dev 
      - libeigen3-dev 
      - libflann-dev 
      - libqhull-dev 
      - libopenni-dev 
      - libboost-dev
      - libboost-system-dev 
      - libboost-filesystem-dev 
      - libboost-thread-dev 
      - libboost-date-time-dev 
      - libboost-iostreams-dev

  pcl:
      after: [vtk]
      source: https://github.com/PointCloudLibrary/pcl
      source-type: git
      source-branch: master
      plugin: cmake
      stage-packages:
        - libusb-1.0-0
        - libglu1-mesa
        - libboost-chrono1.65.1
        - libboost-filesystem1.65.1
        - libboost-iostreams1.65.1
        - libboost-system1.65.1
        - libboost-thread1.65.1
        - libflann1.9
        
      build-packages:
        - libusb-dev 
        - libusb-1.0-0-dev
      configflags:
        - -DCMAKE_BUILD_TYPE=Release 
        - -DBUILD_features=ON 
        - -DBUILD_filters=ON 
        - -DBUILD_geometry=ON 
        - -DBUILD_search=ON 
        - -DBUILD_tools=ON 
        - -DBUILD_visualization=ON 
        - -DBUILD_tracking=ON 
        - -DBUILD_apps=ON 
        - -DPCL_QT_VERSION=5 
        - -DBUILD_apps_point_cloud_editor=ON

  annotationtool:
      after: [vtk, pcl, desktop-qt5]
      source: https://github.com/Kapernikov/cloud_annotation_tool
      source-type: git
      source-branch: master
      plugin: cmake
    
